### ISSUE TITLE
Whit is the best place to tweak fingerings?

### ISSUE THREAD

**Issue by MrMep** [amowry/WARBL2#6]
In the original WARBL firmware, in get_note() there were a lot of special cases and tweaks for single fingerings, now they seem spread all over the code or entirely gone.
I know I'm missing something! What is the best place to do that now?
thanks

**Comment by amowry** [comment]
I got rid of all those special cases because I changed all the fingering charts to have 256 entries. With the original WARBL I was worried about program space so a lot of the charts ignored the thumb hole, etc, and so had 128 entries or fewer. The special cases were needed to account for the holes that weren't included in the charts. It had gotten really messy so I decided to go with full 256 entry charts for everything. That way it's more consistent with how the custom charts work too.

I think you could just add a special case back into get_note() if you need one there.

**Comment by MrMep** [comment]
Thank you. As you might have imagined, I asked mainly to manage half-holed fingerings. I'll put it there.
